ZIP_URL = 'https://raw.githubusercontent.com/burov-kirill/Accounters_Check/master/dist/AccountCheck.7z'
APP_NAME = 'AccountCheck.exe'
VERSION = '1.0.2'
VERSION_URL = 'https://raw.githubusercontent.com/burov-kirill/Accounters_Check/master/__VERS__.txt'
UPDATE_NAME = 'update.exe'
UPDATE_FOLDER = 'config'
UPDATE_URL = 'https://raw.githubusercontent.com/burov-kirill/Updater/master/dist/update.exe'
